import SidebarLayout from "@/components/layout/SidebarLayout";
import { useGetDashboard } from "@workspace/api-client-react";
import { 
  Lightbulb, 
  AlertTriangle, 
  CheckCircle2, 
  TrendingDown, 
  ArrowRight,
  BrainCircuit,
  Utensils,
  PartyPopper
} from "lucide-react";
import { motion } from "framer-motion";

export default function Advisory() {
  const { data: dashboard, isLoading } = useGetDashboard();

  if (isLoading || !dashboard) {
    return (
      <SidebarLayout>
        <div className="w-full h-[60vh] flex items-center justify-center">
          <div className="flex flex-col items-center gap-4 text-muted-foreground animate-pulse">
            <BrainCircuit className="w-10 h-10 animate-pulse text-primary" />
            <p>AI is analyzing your spending patterns...</p>
          </div>
        </div>
      </SidebarLayout>
    );
  }

  const { salary, savingsRate, recentExpenses } = dashboard;

  // Calculate category totals
  const categoryTotals: Record<string, number> = {};
  recentExpenses.forEach(exp => {
    categoryTotals[exp.category] = (categoryTotals[exp.category] || 0) + exp.amount;
  });

  const tips = [];

  // Logic 1: Food > 30% of salary
  const foodTotal = categoryTotals["Food"] || 0;
  const foodPercent = salary > 0 ? (foodTotal / salary) * 100 : 0;
  if (foodPercent > 30) {
    tips.push({
      id: "high-food",
      type: "warning",
      icon: Utensils,
      title: "High Food Expenditure",
      message: `You spent ${foodPercent.toFixed(1)}% of your salary on food. Consider meal prepping to bring this below 20%.`,
      action: "Review Food Expenses"
    });
  }

  // Logic 2: Entertainment > 20%
  const entTotal = categoryTotals["Entertainment"] || 0;
  const entPercent = salary > 0 ? (entTotal / salary) * 100 : 0;
  if (entPercent > 20) {
    tips.push({
      id: "high-ent",
      type: "warning",
      icon: PartyPopper,
      title: "Entertainment Alert",
      message: `Entertainment is taking up ${entPercent.toFixed(1)}% of your budget. Setting a strict weekend budget could help.`,
      action: "Set Entertainment Limit"
    });
  }

  // Logic 3: Savings Rate < 20%
  if (savingsRate < 20) {
    tips.push({
      id: "low-savings",
      type: "critical",
      icon: AlertTriangle,
      title: "Critical: Low Savings Rate",
      message: `Your current savings rate is ${savingsRate.toFixed(1)}%. Financial experts recommend saving at least 20% of your income. Look for major areas to cut back.`,
      action: "Create a Savings Goal"
    });
  } else if (savingsRate >= 20) {
    tips.push({
      id: "good-savings",
      type: "success",
      icon: CheckCircle2,
      title: "Excellent Savings Rate",
      message: `Great job! You are saving ${savingsRate.toFixed(1)}% of your income. Consider investing the surplus to compound your wealth.`,
      action: "Explore Investments"
    });
  }

  // Generic tip if nothing triggers
  if (tips.length === 1 && tips[0].type === "success") {
    tips.push({
      id: "general",
      type: "info",
      icon: TrendingDown,
      title: "Optimize Subscriptions",
      message: "Even with good savings, auditing recurring bills every 6 months can find hidden leaks in your cash flow.",
      action: "Audit Subscriptions"
    });
  }

  return (
    <SidebarLayout>
      <div className="space-y-8 pb-10">
        <header className="mb-10 text-center max-w-2xl mx-auto">
          <div className="w-16 h-16 bg-primary/10 rounded-2xl flex items-center justify-center mx-auto mb-6">
            <BrainCircuit className="w-8 h-8 text-primary" />
          </div>
          <h1 className="text-3xl sm:text-4xl font-display font-bold tracking-tight text-foreground mb-4">
            AI Financial Advisory
          </h1>
          <p className="text-muted-foreground text-lg">
            Personalized insights generated by analyzing your recent spending patterns against your income.
          </p>
        </header>

        <div className="max-w-4xl mx-auto space-y-6">
          {tips.map((tip, index) => {
            const Icon = tip.icon;
            
            // Theme setup based on tip type
            let bgClass = "bg-card";
            let borderClass = "border-border";
            let iconBgClass = "bg-secondary";
            let iconColorClass = "text-muted-foreground";

            if (tip.type === "warning") {
              borderClass = "border-orange-500/30";
              iconBgClass = "bg-orange-500/10";
              iconColorClass = "text-orange-500";
            } else if (tip.type === "critical") {
              borderClass = "border-destructive/40";
              iconBgClass = "bg-destructive/10";
              iconColorClass = "text-destructive";
              bgClass = "bg-destructive/5";
            } else if (tip.type === "success") {
              borderClass = "border-success/30";
              iconBgClass = "bg-success/10";
              iconColorClass = "text-success";
            } else if (tip.type === "info") {
              borderClass = "border-primary/30";
              iconBgClass = "bg-primary/10";
              iconColorClass = "text-primary";
            }

            return (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.15 }}
                key={tip.id}
                className={`p-6 sm:p-8 rounded-3xl border ${bgClass} ${borderClass} shadow-lg relative overflow-hidden group`}
              >
                <div className="flex flex-col sm:flex-row gap-6 items-start">
                  <div className={`p-4 rounded-2xl shrink-0 ${iconBgClass}`}>
                    <Icon className={`w-8 h-8 ${iconColorClass}`} />
                  </div>
                  
                  <div className="flex-1 space-y-3">
                    <h3 className="text-xl font-bold text-foreground">{tip.title}</h3>
                    <p className="text-muted-foreground leading-relaxed text-base">
                      {tip.message}
                    </p>
                    <div className="pt-3">
                      <button className={`inline-flex items-center gap-2 text-sm font-bold ${iconColorClass} hover:opacity-80 transition-opacity`}>
                        {tip.action} <ArrowRight className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>
              </motion.div>
            );
          })}
          
          {tips.length === 0 && (
            <div className="text-center p-12 bg-card border border-border rounded-3xl">
              <Lightbulb className="w-12 h-12 text-muted-foreground mx-auto mb-4 opacity-50" />
              <p className="text-lg text-muted-foreground">Add more expenses to get personalized financial advice.</p>
            </div>
          )}
        </div>
      </div>
    </SidebarLayout>
  );
}
